# seed_data/routes.py の routes_to_seed を、この内容に完全に置き換えてください

routes_to_seed = [
    # (ルート名, plan_type, subject_id)
    ('english_standard', 'standard', 1),
    ('math_bunkei_standard', 'standard', 2),
    ('math_rikei_standard', 'standard', 2),
    ('gendai_standard', 'standard', 3),
    ('kobun_standard', 'standard', 4),
    ('kanbun_standard', 'standard', 5),
    ('world_history_standard', 'standard', 6),
    ('japanese_history_standard', 'standard', 7),
    ('geo_standard', 'standard', 8),
    ('politics_econ_standard', 'standard', 9),
    ('ethics_standard', 'standard', 10),
    ('physics_standard', 'standard', 11),
    ('chemistry_standard', 'standard', 12),
    ('biology_standard', 'standard', 13),
    ('geo_sci_standard', 'standard', 14),
    ('shoronbun_standard', 'standard', 15),
]

route_steps_human_readable = [
    # 英語ルート
    ('english_standard', 'eng_n01', 1, '日東駒専レベル', '英単語', 1),
    ('english_standard', 'eng_n02', 2, '日東駒専レベル', '英単語', 0),
    ('english_standard', 'eng_n03', 3, '日東駒専レベル', '英文法', 1),
    ('english_standard', 'eng_n04', 4, '日東駒専レベル', '英文法', 1),
    ('english_standard', 'eng_n05', 5, '日東駒専レベル', '英文解釈', 1),
    ('english_standard', 'eng_n06', 6, '日東駒専レベル', '英語長文', 1),
    ('english_standard', 'eng_n07', 7, '日東駒専レベル', '英語長文', 1),
    ('english_standard', 'level_check_nittokomasen_eng', 8, '日東駒専レベル', 'レベルチェック', 1),
    ('english_standard', 'eng_m01', 9, 'MARCHレベル', '英単語', 1),
    ('english_standard', 'eng_m02', 10, 'MARCHレベル', '英単語', 0),
    ('english_standard', 'eng_m03', 11, 'MARCHレベル', '英文法', 1),
    ('english_standard', 'eng_m04', 12, 'MARCHレベル', '英文法', 1),
    ('english_standard', 'eng_m05', 13, 'MARCHレベル', '英文解釈', 1),
    ('english_standard', 'eng_m06', 14, 'MARCHレベル', '英文解釈', 0),
    ('english_standard', 'eng_m07', 15, 'MARCHレベル', '英語長文', 1),
    ('english_standard', 'eng_m08', 16, 'MARCHレベル', '英語長文', 1),
    ('english_standard', 'eng_m09', 17, 'MARCHレベル', '英語長文', 1),
    ('english_standard', 'level_check_march_eng', 18, 'MARCHレベル', 'レベルチェック', 1),
    ('english_standard', 'eng_s01', 19, '早慶レベル', '英単語', 1),
    ('english_standard', 'eng_s02', 20, '早慶レベル', '英単語', 0),
    ('english_standard', 'eng_s03', 21, '早慶レベル', '英文法', 1),
    ('english_standard', 'eng_s04', 22, '早慶レベル', '英文法', 1),
    ('english_standard', 'eng_s05', 23, '早慶レベル', '英文解釈', 1),
    ('english_standard', 'eng_s06', 24, '早慶レベル', '英文解釈', 0),
    ('english_standard', 'eng_s07', 25, '早慶レベル', '英語長文', 1),
    ('english_standard', 'eng_s08', 26, '早慶レベル', '英語長文', 1),
    ('english_standard', 'eng_s09', 27, '早慶レベル', '英語長文', 1),
    ('english_standard', 'eng_sp01', 28, '特殊形式', 'リスニング', 1),
    ('english_standard', 'eng_sp02', 29, '特殊形式', '英作文', 1),
    ('english_standard', 'eng_sp03', 30, '特殊形式', '英作文', 1),

    # 文系数学ルート
    ('math_bunkei_standard', 'math_b_n01', 1, '日東駒専レベル', '基礎', 1),
    ('math_bunkei_standard', 'math_b_n02', 2, '日東駒専レベル', '基礎', 1),
    ('math_bunkei_standard', 'level_check_nittokomasen_math_b', 3, '日東駒専レベル', 'レベルチェック', 1),
    ('math_bunkei_standard', 'math_b_m01', 4, 'MARCHレベル', '標準', 1),
    ('math_bunkei_standard', 'math_b_m02', 5, 'MARCHレベル', '応用', 1),
    ('math_bunkei_standard', 'level_check_march_math_b', 6, 'MARCHレベル', 'レベルチェック', 1),
    ('math_bunkei_standard', 'math_b_s01', 7, '早慶レベル', '最難関', 1),

    # 理系数学ルート
    ('math_rikei_standard', 'math_r_n01', 1, '日東駒専レベル', '基礎', 1),
    ('math_rikei_standard', 'level_check_nittokomasen_math_r', 2, '日東駒専レベル', 'レベルチェック', 1),
    ('math_rikei_standard', 'math_r_m01', 3, 'MARCHレベル', '網羅', 1),
    ('math_rikei_standard', 'math_r_m02', 4, 'MARCHレベル', '網羅', 0),
    ('math_rikei_standard', 'math_r_m03', 5, 'MARCHレベル', '橋渡し', 1),
    ('math_rikei_standard', 'math_r_m04', 6, 'MARCHレベル', '橋渡し', 0),
    ('math_rikei_standard', 'level_check_march_math_r', 7, 'MARCHレベル', 'レベルチェック', 1),
    ('math_rikei_standard', 'math_r_s01', 8, '早慶レベル', '橋渡し', 1),
    ('math_rikei_standard', 'math_r_s02', 9, '早慶レベル', '応用', 1),
    ('math_rikei_standard', 'math_r_s03', 10, '早慶レベル', '応用', 0),

    # 現代文ルート
    ('gendai_standard', 'koku_g_n01', 1, '日東駒専レベル', '語彙', 1),
    ('gendai_standard', 'koku_g_n02', 2, '日東駒専レベル', '語彙', 0),
    ('gendai_standard', 'koku_g_n03', 3, '日東駒専レベル', '漢字', 1),
    ('gendai_standard', 'koku_g_n04', 4, '日東駒専レベル', '読解', 1),
    ('gendai_standard', 'koku_g_n05', 5, '日東駒専レベル', '読解', 1),
    ('gendai_standard', 'level_check_nittokomasen_koku_g', 6, '日東駒専レベル', 'レベルチェック', 1),
    ('gendai_standard', 'koku_g_m01', 7, 'MARCHレベル', '読解', 1),
    ('gendai_standard', 'level_check_march_koku_g', 8, 'MARCHレベル', 'レベルチェック', 1),
    ('gendai_standard', 'koku_g_s01', 9, '早慶レベル', '読解', 1),
    ('gendai_standard', 'koku_g_s02', 10, '早慶レベル', '読解', 0),

    # 古文ルート
    ('kobun_standard', 'koku_k_n01', 1, '日東駒専レベル', '単語', 1),
    ('kobun_standard', 'koku_k_n02', 2, '日東駒専レベル', '単語', 0),
    ('kobun_standard', 'koku_k_n03', 3, '日東駒専レベル', '単語', 0),
    ('kobun_standard', 'koku_k_n04', 4, '日東駒専レベル', '文法', 1),
    ('kobun_standard', 'koku_k_n05', 5, '日東駒専レベル', '文法', 0),
    ('kobun_standard', 'koku_k_n06', 6, '日東駒専レベル', '文法', 1),
    ('kobun_standard', 'koku_k_n07', 7, '日東駒専レベル', '読解', 1),
    ('kobun_standard', 'koku_k_n08', 8, '日東駒専レベル', '読解', 1),
    ('kobun_standard', 'level_check_nittokomasen_koku_k', 9, '日東駒専レベル', 'レベルチェック', 1),
    ('kobun_standard', 'koku_k_m01', 10, 'MARCHレベル', '単語', 1),
    ('kobun_standard', 'koku_k_m02', 11, 'MARCHレベル', '読解', 1),
    ('kobun_standard', 'koku_k_m03', 12, 'MARCHレベル', '読解', 1),
    ('kobun_standard', 'level_check_march_koku_k', 13, 'MARCHレベル', 'レベルチェック', 1),
    ('kobun_standard', 'koku_k_s01', 14, '早慶レベル', '読解', 1),
    ('kobun_standard', 'koku_k_s02', 15, '早慶レベル', '読解', 1),

    # 漢文ルート
    ('kanbun_standard', 'koku_h_n01', 1, '日東駒専レベル', '句法', 1),
    ('kanbun_standard', 'koku_h_n02', 2, '日東駒専レベル', '句法', 1),
    ('kanbun_standard', 'koku_h_n03', 3, '日東駒専レベル', '演習', 1),
    ('kanbun_standard', 'level_check_nittokomasen_koku_h', 4, '日東駒専レベル', 'レベルチェック', 1),
    ('kanbun_standard', 'koku_h_s01', 5, 'MARCH・早慶レベル', '記述対策', 1),
    ('kanbun_standard', 'koku_h_s02', 6, 'MARCH・早慶レベル', '演習', 1),
    
    # 日本史ルート
    ('japanese_history_standard', 'hist_j_n01', 1, '日東駒専レベル', '講義', 1),
    ('japanese_history_standard', 'hist_j_n02', 2, '日東駒専レベル', '用語', 1),
    ('japanese_history_standard', 'hist_j_n03', 3, '日東駒専レベル', '演習', 1),
    ('japanese_history_standard', 'level_check_nittokomasen_hist_j', 4, '日東駒専レベル', 'レベルチェック', 1),
    ('japanese_history_standard', 'hist_j_m01', 5, 'MARCHレベル', '講義', 1),
    ('japanese_history_standard', 'hist_j_m02', 6, 'MARCHレベル', '講義', 0),
    ('japanese_history_standard', 'hist_j_m03', 7, 'MARCHレベル', '用語', 1),
    ('japanese_history_standard', 'hist_j_m04', 8, 'MARCHレベル', '演習', 1),
    ('japanese_history_standard', 'hist_j_m05', 0, 'MARCHレベル', '補助教材', 1),
    ('japanese_history_standard', 'hist_j_m06', 0, 'MARCHレベル', '補助教材', 1),
    ('japanese_history_standard', 'level_check_march_hist_j', 11, 'MARCHレベル', 'レベルチェック', 1),
    ('japanese_history_standard', 'hist_j_s01', 12, '早慶レベル', '史料対策', 1),
    ('japanese_history_standard', 'hist_j_s02', 13, '早慶レベル', '論述対策', 1),

    # 世界史ルート
    ('world_history_standard', 'hist_w_n01', 1, '日東駒専レベル', '講義', 1),
    ('world_history_standard', 'hist_w_n02', 2, '日東駒専レベル', '用語', 1),
    ('world_history_standard', 'hist_w_n03', 3, '日東駒専レベル', '演習', 1),
    ('world_history_standard', 'level_check_nittokomasen_hist_w', 4, '日東駒専レベル', 'レベルチェック', 1),
    ('world_history_standard', 'hist_w_m01', 5, 'MARCHレベル', '講義', 1),
    ('world_history_standard', 'hist_w_m02', 6, 'MARCHレベル', '講義', 0),
    ('world_history_standard', 'hist_w_m03', 7, 'MARCHレベル', '用語', 1),
    ('world_history_standard', 'hist_w_m04', 8, 'MARCHレベル', '演習', 1),
    ('world_history_standard', 'hist_w_m05', 0, 'MARCHレベル', '補助教材', 1),
    ('world_history_standard', 'level_check_march_hist_w', 10, 'MARCHレベル', 'レベルチェック', 1),
    ('world_history_standard', 'hist_w_s01', 11, '早慶レベル', '演習', 1),
    ('world_history_standard', 'hist_w_s02', 12, '早慶レベル', '用語', 1),
    ('world_history_standard', 'hist_w_s03', 13, '早慶レベル', '論述対策', 1),

    # 地理ルート
    ('geo_standard', 'geo_n01', 1, '日東駒専レベル', '講義', 1),
    ('geo_standard', 'geo_n02', 2, '日東駒専レベル', '講義', 1),
    ('geo_standard', 'geo_n03', 3, '日東駒専レベル', '演習', 1),
    ('geo_standard', 'level_check_nittokomasen_geo', 4, '日東駒専レベル', 'レベルチェック', 1),
    ('geo_standard', 'geo_m01', 5, 'MARCHレベル', '演習', 1),
    ('geo_standard', 'level_check_march_geo', 6, 'MARCHレベル', 'レベルチェック', 1),
    ('geo_standard', 'geo_s01', 7, '早慶・国公立レベル', '論述対策', 1),
    ('geo_standard', 'geo_s02', 0, '早慶・国公立レベル', '補助教材', 1),

    # 政治・経済ルート
    ('politics_econ_standard', 'poli_n01', 1, '日東駒専レベル', '講義', 1),
    ('politics_econ_standard', 'level_check_nittokomasen_poli', 2, '日東駒専レベル', 'レベルチェック', 1),
    ('politics_econ_standard', 'poli_m01', 3, 'MARCH・早慶レベル', '講義', 1),
    ('politics_econ_standard', 'poli_m02', 4, 'MARCH・早慶レベル', '演習', 1),
    ('politics_econ_standard', 'poli_m03', 5, 'MARCH・早慶レベル', '演習', 0),

    # 倫理ルート
    ('ethics_standard', 'eth_n01', 1, '日東駒専レベル', '講義', 1),
    ('ethics_standard', 'level_check_nittokomasen_eth', 2, '日東駒専レベル', 'レベルチェック', 1),
    ('ethics_standard', 'eth_m01', 3, 'MARCH・早慶レベル', '用語', 1),

    # 物理ルート
    ('physics_standard', 'phys_n01', 1, '日東駒専レベル', '講義', 1),
    ('physics_standard', 'phys_n02', 2, '日東駒専レベル', '演習', 1),
    ('physics_standard', 'phys_n03', 3, '日東駒専レベル', '演習', 1),
    ('physics_standard', 'level_check_nittokomasen_phsy', 4, '日東駒専レベル', 'レベルチェック', 1),
    ('physics_standard', 'phys_m01', 5, 'MARCHレベル', '演習', 1),
    ('physics_standard', 'level_check_march_phsy', 6, 'MARCHレベル', 'レベルチェック', 1),
    ('physics_standard', 'phys_s01', 7, '早慶レベル', '演習', 1),
    ('physics_standard', 'phys_s02', 8, '早慶レベル', '演習', 0),

    # 化学ルート
    ('chemistry_standard', 'chem_n01', 1, '日東駒専レベル', '講義', 1),
    ('chemistry_standard', 'chem_n02', 2, '日東駒専レベル', '講義', 0),
    ('chemistry_standard', 'chem_n03', 3, '日東駒専レベル', '演習', 1),
    ('chemistry_standard', 'chem_n04', 4, '日東駒専レベル', '演習', 1),
    ('chemistry_standard', 'level_check_nittokomasen_chem', 5, '日東駒専レベル', 'レベルチェック', 1),
    ('chemistry_standard', 'chem_m01', 6, 'MARCHレベル', '講義', 1),
    ('chemistry_standard', 'chem_m02', 7, 'MARCHレベル', '講義', 1),
    ('chemistry_standard', 'chem_m03', 8, 'MARCHレベル', '講義', 1),
    ('chemistry_standard', 'chem_m04', 9, 'MARCHレベル', '演習', 1),
    ('chemistry_standard', 'level_check_march_chem', 10, 'MARCHレベル', 'レベルチェック', 1),
    ('chemistry_standard', 'chem_s01', 11, '早慶レベル', '演習', 1),
    ('chemistry_standard', 'chem_s02', 12, '早慶レベル', '演習', 0),
    ('chemistry_standard', 'chem_s03', 13, '早慶レベル', '演習', 0),

    # 生物ルート
    ('biology_standard', 'bio_n01', 1, '日東駒専レベル', '講義', 1),
    ('biology_standard', 'bio_n02', 2, '日東駒専レベル', '演習', 1),
    ('biology_standard', 'level_check_nittokomasen_bio', 3, '日東駒専レベル', 'レベルチェック', 1),
    ('biology_standard', 'bio_m01', 4, 'MARCHレベル', '講義・演習', 1),
    ('biology_standard', 'level_check_march_bio', 5, 'MARCHレベル', 'レベルチェック', 1),
    ('biology_standard', 'bio_s01', 6, '早慶レベル', '演習', 1),
    ('biology_standard', 'bio_s02', 7, '早慶レベル', '記述対策', 1),

    # 地学ルート
    ('geo_sci_standard', 'geo_sci_n01', 1, '日東駒専レベル', '講義', 1),
    ('geo_sci_standard', 'geo_sci_n02', 2, '日東駒専レベル', '講義', 0),
    ('geo_sci_standard', 'geo_sci_n03', 3, '日東駒専レベル', '演習', 1),
    ('geo_sci_standard', 'level_check_nittokomasen_geo_sci', 4, '日東駒専レベル', 'レベルチェック', 1),
    ('geo_sci_standard', 'geo_sci_s01', 5, 'MARCH・早慶・国公立レベル', '講義', 1),
    ('geo_sci_standard', 'geo_sci_s02', 6, 'MARCH・早慶・国公立レベル', '演習', 1),
    ('geo_sci_standard', 'geo_sci_s03', 7, 'MARCH・早慶・国公立レベル', '補助教材', 1),
    
    # 小論文ルート
    ('shoronbun_standard', 'shoronbun_task_01', 1, '日東駒専レベル', '基礎知識', 1),
    ('shoronbun_standard', 'shoronbun_task_02', 2, 'MARCHレベル', '書き方の型', 1),
    ('shoronbun_standard', 'shoronbun_task_03', 3, '早慶レベル', '実践演習', 1),
]