"""Add official_mock_exam table

Revision ID: 3642ef8404ad
Revises: ac39958e4f7b
Create Date: 2025-09-16 14:34:34.836358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3642ef8404ad'
down_revision = 'ac39958e4f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universities')
    op.drop_table('user_subjects')
    op.drop_table('users')
    op.drop_table('progress')
    op.drop_table('user_hidden_tasks')
    op.drop_table('study_logs')
    op.drop_table('routes')
    op.drop_table('faculties')
    op.drop_table('mock_exams')
    op.drop_table('subjects')
    op.drop_table('user_continuous_task_selections')
    op.drop_table('weaknesses')
    op.drop_table('books')
    op.drop_table('route_steps')
    op.drop_table('user_sequential_task_selections')
    op.drop_table('subject_strategies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_strategies',
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_html', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('user_sequential_task_selections',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.VARCHAR(), nullable=False),
    sa.Column('selected_task_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('route_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('route_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('step_order', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('is_main', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('youtube_query', sa.VARCHAR(), nullable=True),
    sa.Column('duration_weeks', sa.INTEGER(), nullable=False),
    sa.Column('task_type', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('weaknesses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('topic', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_continuous_task_selections',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('selected_task_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'subject_id', 'level', 'category')
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mock_exams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exam_name', sa.VARCHAR(), nullable=False),
    sa.Column('exam_date', sa.DATE(), nullable=False),
    sa.Column('results_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('university_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('plan_type', sa.VARCHAR(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_hidden_tasks',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    op.create_table('progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(), nullable=False),
    sa.Column('is_completed', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_progress_subject_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('grade', sa.VARCHAR(), nullable=False),
    sa.Column('school', sa.VARCHAR(), nullable=False),
    sa.Column('faculty', sa.VARCHAR(), nullable=False),
    sa.Column('plan_type', sa.VARCHAR(), nullable=False),
    sa.Column('course_type', sa.VARCHAR(), nullable=True),
    sa.Column('prefecture', sa.VARCHAR(), nullable=True),
    sa.Column('target_exam_date', sa.DATE(), nullable=True),
    sa.Column('learning_style', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_subjects',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'subject_id')
    )
    op.create_table('universities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('kana_name', sa.VARCHAR(), nullable=False),
    sa.Column('level', sa.VARCHAR(), nullable=False),
    sa.Column('info_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
