"""Enhance MockExam models

Revision ID: 9f7de42edc4c
Revises: 156b16587677
Create Date: 2025-09-23 17:49:34.696377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7de42edc4c'
down_revision = '156b16587677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_exam_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('ranking', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mock_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(), nullable=True))
        batch_op.drop_column('results_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('results_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('provider')

    op.drop_table('mock_exam_results')
    # ### end Alembic commands ###
