"""Remove starting level feature

Revision ID: ac39958e4f7b
Revises: bdcfc635c675
Create Date: 2025-09-10 17:37:20.986090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac39958e4f7b'
down_revision = 'bdcfc635c675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('starting_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_level', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
