"""Add subject_id to progress table

Revision ID: c58bc56d81ce
Revises: 2d0cfa1b7de3
Create Date: 2025-09-09 13:06:07.844933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58bc56d81ce'
down_revision = '2d0cfa1b7de3'
branch_labels = None
depends_on = None


# migrations/versions/...._add_subject_id_to_progress_table.py

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True)) # 一時的にNULLを許可
        
        # ▼▼▼ 外部キー制約に名前を付けて、ここに追加 ▼▼▼
        batch_op.create_foreign_key(
            "fk_progress_subject_id", "subjects", ["subject_id"], ["id"]
        )

    # NULLを許可しない設定に戻す（任意ですが、より安全です）
    with op.batch_alter_table('progress', schema=None) as batch_op:
         batch_op.alter_column('subject_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
