"""Alter official_mock_exam table

Revision ID: e2014c7aead4
Revises: a25cfa19634d
Create Date: 2025-09-17 19:55:25.523456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2014c7aead4'
down_revision = 'a25cfa19634d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_mock_exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_grade', sa.String(length=50), nullable=True))
        batch_op.alter_column('app_start_date',
            existing_type=sa.DATE(),
            nullable=True)
        batch_op.alter_column('app_end_date',
            existing_type=sa.DATE(),
            nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_mock_exam', schema=None) as batch_op:
        batch_op.alter_column('app_end_date',
            existing_type=sa.DATE(),
            nullable=False)
        batch_op.alter_column('app_start_date',
            existing_type=sa.DATE(),
            nullable=False)
        batch_op.drop_column('target_grade')

    # ### end Alembic commands ###