"""Alter official_mock_exam table

Revision ID: e2014c7aead4
Revises: a25cfa19634d
Create Date: 2025-09-17 17:16:36.229538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2014c7aead4'
down_revision = 'a25cfa19634d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_mock_exam', sa.Column('target_grade', sa.String(length=50), nullable=True))
    op.alter_column('official_mock_exam', 'app_start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('official_mock_exam', 'app_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('official_mock_exam', 'app_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('official_mock_exam', 'app_start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('official_mock_exam', 'target_grade')
    # ### end Alembic commands ###
