"""Add comment to StudyLog

Revision ID: f01e646cedee
Revises: 9f7de42edc4c
Create Date: 2025-09-24 13:10:29.460999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01e646cedee'
down_revision = '9f7de42edc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
